recursive: true
bail: true
inline-diffs: true
reporter: spec
check-leaks: true
extension:
  - ts
spec:
  - test/**/*.spec.ts
node-option:
  - experimental-specifier-resolution=node
  - loader=ts-node/esm