language: node_js
dist: xenial
notifications:
  email:
    recipients:
      - middleware@hexonet.net
    on_success: never
    on_failure: always
node_js:
  - "11"
  - "10"
  - "9"
# Trigger a push build on master and dependabot branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^dependabot.*$/
before_install:
  - npm prune
install:
  - travis_retry npm i
before_script:
  - npm run build
  - npm run lint
script:
  - npm run test
jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npx semantic-release
