name: Release
on: 
  # will run for every branch, except tags. See RSRMID-206.
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - "**"
    # Sequence of patterns matched against refs/tags
    tags-ignore: 
      - "**"
  pull_request:
    branches:
      - "**"
    tags-ignore: 
      - "**"

jobs:
  test:
    name: Test @ NodeJS - x86 - ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.actor != 'dependabot[bot]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup NodeJS LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
      - name: Super Linter Code Base
        uses: github/super-linter@v4
        env:
          FILTER_REGEX_INCLUDE: "/src/*"
          DEFAULT_BRANCH: master
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
      - name: Build & Validation
        run: |
          npm ci
          npm run build
          npm run lint
          npm run test
  release:
    name: Release @ NodeJS LTS - x86 - ubuntu-latest
    runs-on: ubuntu-latest
    needs:
      - test
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup NodeJS LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
          cache: npm          
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        # TODO move npm run documentation to semantic-release
        run: |
          npm run build
          npm run documentation
          npx semantic-release
