name: Release
on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: Build
    uses: ./.github/workflows/test.yml

  release:
    name: Release @ ubuntu-latest
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup NodeJS ${{ vars.RTLDEV_MW_CI_NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: '${{ vars.RTLDEV_MW_CI_NODE_VERSION }}'
          check-latest: true
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          RTLDEV_MW_NOTIFICATION_URI: ${{ secrets.RTLDEV_MW_NOTIFICATION_URI }}
        # TODO move npm run documentation to semantic-release
        run: |
          npm run documentation
          npx semantic-release
