name: Release
on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: Build
    uses: ./.github/workflows/test.yml

  release:
    name: Release @ NodeJS LTS - x86 - ubuntu-latest
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup NodeJS LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        # TODO move npm run documentation to semantic-release
        run: |
          npm run documentation
          npx semantic-release
